package com.vowme.util;

public interface AppConstants {
	String CAUSE = "CAUSE";
	String INTEREST = "INTEREST";
	String DURATION = "DURATION";
	String EXPLANATION = "EXPLANATION";
	String REQUIREMENTS = "REQUIREMENT";
	String LANGUAGUES = "LANGUAGUE";
	String TRANSPORTS = "TRANSPORT";
	String TYPEOFCARS = "TYPEOFCAR";
	String TSHIRTSIZE = "TSHIRTSIZE";
	String TITLES = "TITLE";
	String PROSKILLS = "classifications";
	String EXPERIENCES = "EXPERIENCE";
	String SUBPROSKILLS = "SUBPROSKILL";
	String NOTIFICATIONFREQUENCIES = "NOTIFICATIONFREQUENCY";
	String LOCATIONS = "LOCATION";
	String AVAIBILITYFILTER = "AVAIBILITYFILTER";
	String AVAIBILITY = "AVAIBILITY";
}
